"""
Output Pydantic models for the AI Farm Analyst.

The LLM is forced to return JSON that matches `AnalystReport`.
Every field is typed and described so the schema passed to Gemini
is self-documenting.
"""

from __future__ import annotations

from typing import List, Optional
from pydantic import BaseModel, Field
from typing import Literal


class FertilizerRecommendation(BaseModel):
    """Concrete fertilizer advice for the current crop stage."""

    fertilizer_name: str = Field(
        description="Common fertilizer name, e.g. 'Urea', 'DAP', 'MOP'."
    )
    quantity_kg_per_acre: float = Field(
        gt=0.0,
        description="Recommended application rate in kg per acre.",
    )
    total_quantity_kg: float = Field(
        gt=0.0,
        description="Total quantity needed for the entire farm (quantity_kg_per_acre × farm_size_acres).",
    )
    application_method: str = Field(
        description="How to apply, e.g. 'Broadcast and incorporate', 'Fertigation', 'Side-dress'."
    )
    timing_notes: str = Field(
        description="When and under what conditions to apply, including any weather caveats."
    )


class Alert(BaseModel):
    """A time-sensitive warning or advisory for the farmer."""

    alert_type: Literal["Disease", "Pest", "Weather", "Soil", "Irrigation", "General"] = Field(
        description="Category of the alert."
    )
    severity: Literal["Critical", "Warning", "Info"] = Field(
        description="How urgent the alert is: Critical requires immediate action."
    )
    title: str = Field(
        description="Short alert title, max ~8 words."
    )
    description: str = Field(
        description="Detailed explanation of the risk and what the farmer should watch for."
    )


class ActionItem(BaseModel):
    """A single, concrete task the farmer must do."""

    action: str = Field(
        description="Clear imperative description of what to do, e.g. 'Apply 45 kg Urea per acre'."
    )
    priority: Literal["Critical", "High", "Medium", "Low"] = Field(
        description="Relative urgency of this action."
    )
    timing: str = Field(
        description="When to do it, e.g. 'Today', 'After Wednesday', 'Within 3 days'."
    )
    reason: str = Field(
        description="One-sentence explanation of why this action is needed."
    )


class AnalystReport(BaseModel):
    """
    Structured advisory report generated by the AI Farm Analyst.

    This is the fixed output schema — Gemini is configured to always
    return JSON that validates against this model.
    """

    greeting: str = Field(
        description="Friendly, localised greeting to open the report, e.g. 'Namaste!'"
    )
    crop_stage: str = Field(
        description=(
            "Current crop growth stage inferred from sowing date and crop type, "
            "e.g. 'Vegetative (25 days old)', 'Flowering', 'Germination'."
        )
    )
    situation_summary: str = Field(
        description=(
            "Two-to-three sentence plain-language overview of the farm's current "
            "situation combining soil, weather, and crop data."
        )
    )
    alerts: List[Alert] = Field(
        default_factory=list,
        description="List of active warnings or advisories. May be empty if all is well.",
    )
    action_items: List[ActionItem] = Field(
        description="Prioritised list of concrete tasks the farmer should act on.",
    )
    fertilizer_recommendation: Optional[FertilizerRecommendation] = Field(
        default=None,
        description="Fertilizer advice if a deficiency and crop stage warrant it. Null otherwise.",
    )
    irrigation_recommendation: Optional[str] = Field(
        default=None,
        description=(
            "Irrigation guidance in plain language. Null if not relevant "
            "(e.g. current moisture is optimal or it is rainfed with adequate rain)."
        ),
    )
    pest_disease_watch: List[str] = Field(
        default_factory=list,
        description=(
            "List of specific pests or diseases to watch for, given current crop stage "
            "and weather conditions."
        ),
    )
    full_advisory: str = Field(
        description=(
            "The complete human-readable advisory paragraph(s) that the farmer "
            "should hear or read. Should be warm, clear, actionable and in plain language."
        )
    )
